#![doc = "This file was automatically generated by the varlink rust generator"]
#![allow(non_camel_case_types)]
#![allow(non_snake_case)]
use serde_derive::{Deserialize, Serialize};
use serde_json;
use std::io::BufRead;
use std::sync::{Arc, RwLock};
use varlink::{self, CallTrait};
#[allow(dead_code)]
#[derive(Clone, PartialEq, Debug)]
pub enum ErrorKind {
    Varlink_Error,
    VarlinkReply_Error,
    NmStatePluginErr(Option<NmStatePluginErr_Args>),
}
impl ::std::fmt::Display for ErrorKind {
    fn fmt(&self, f: &mut ::std::fmt::Formatter) -> ::std::fmt::Result {
        match self {
            ErrorKind::Varlink_Error => write!(f, "Varlink Error"),
            ErrorKind::VarlinkReply_Error => write!(f, "Varlink error reply"),
            ErrorKind::NmStatePluginErr(v) => {
                write!(f, "io.nmstate.plugin.NmStatePluginErr: {:#?}", v)
            }
        }
    }
}
pub struct Error(
    pub ErrorKind,
    pub Option<Box<dyn std::error::Error + 'static + Send + Sync>>,
    pub Option<&'static str>,
);
impl Error {
    #[allow(dead_code)]
    pub fn kind(&self) -> &ErrorKind {
        &self.0
    }
}
impl From<ErrorKind> for Error {
    fn from(e: ErrorKind) -> Self {
        Error(e, None, None)
    }
}
impl std::error::Error for Error {
    fn source(&self) -> Option<&(dyn std::error::Error + 'static)> {
        self.1
            .as_ref()
            .map(|e| e.as_ref() as &(dyn std::error::Error + 'static))
    }
}
impl std::fmt::Display for Error {
    fn fmt(&self, f: &mut std::fmt::Formatter) -> std::fmt::Result {
        std::fmt::Display::fmt(&self.0, f)
    }
}
impl std::fmt::Debug for Error {
    fn fmt(&self, f: &mut std::fmt::Formatter) -> std::fmt::Result {
        use std::error::Error as StdError;
        if let Some(ref o) = self.2 {
            std::fmt::Display::fmt(o, f)?;
        }
        std::fmt::Debug::fmt(&self.0, f)?;
        if let Some(e) = self.source() {
            std::fmt::Display::fmt("\nCaused by:\n", f)?;
            std::fmt::Debug::fmt(&e, f)?;
        }
        Ok(())
    }
}
#[allow(dead_code)]
pub type Result<T> = std::result::Result<T, Error>;
impl From<varlink::Error> for Error {
    fn from(e: varlink::Error) -> Self {
        match e.kind() {
            varlink::ErrorKind::VarlinkErrorReply(r) => Error(
                ErrorKind::from(r),
                Some(Box::from(e)),
                Some(concat!(file!(), ":", line!(), ": ")),
            ),
            _ => Error(
                ErrorKind::Varlink_Error,
                Some(Box::from(e)),
                Some(concat!(file!(), ":", line!(), ": ")),
            ),
        }
    }
}
#[allow(dead_code)]
impl Error {
    pub fn source_varlink_kind(&self) -> Option<&varlink::ErrorKind> {
        use std::error::Error as StdError;
        let mut s: &dyn StdError = self;
        while let Some(c) = s.source() {
            let k = self
                .source()
                .and_then(|e| e.downcast_ref::<varlink::Error>())
                .and_then(|e| Some(e.kind()));
            if k.is_some() {
                return k;
            }
            s = c;
        }
        None
    }
}
impl From<&varlink::Reply> for ErrorKind {
    #[allow(unused_variables)]
    fn from(e: &varlink::Reply) -> Self {
        match e {
            varlink::Reply {
                error: Some(ref t), ..
            } if t == "io.nmstate.plugin.NmStatePluginErr" => match e {
                varlink::Reply {
                    parameters: Some(p),
                    ..
                } => match serde_json::from_value(p.clone()) {
                    Ok(v) => ErrorKind::NmStatePluginErr(v),
                    Err(_) => ErrorKind::NmStatePluginErr(None),
                },
                _ => ErrorKind::NmStatePluginErr(None),
            },
            _ => ErrorKind::VarlinkReply_Error,
        }
    }
}
pub trait VarlinkCallError: varlink::CallTrait {
    fn reply_nm_state_plugin_err(
        &mut self,
        r#kind: String,
        r#error_message: String,
        r#logs: Vec<String>,
    ) -> varlink::Result<()> {
        self.reply_struct(varlink::Reply::error(
            "io.nmstate.plugin.NmStatePluginErr",
            Some(
                serde_json::to_value(NmStatePluginErr_Args {
                    r#kind,
                    r#error_message,
                    r#logs,
                })
                .map_err(varlink::map_context!())?,
            ),
        ))
    }
}
impl<'a> VarlinkCallError for varlink::Call<'a> {}
#[derive(Serialize, Deserialize, Debug, PartialEq, Clone)]
pub struct r#NetIface {
    pub r#name: String,
    pub r#type: String,
}
#[derive(Serialize, Deserialize, Debug, PartialEq, Clone)]
pub struct r#NetState {
    pub r#interfaces: Option<Vec<NetIface>>,
}
#[derive(Serialize, Deserialize, Debug, PartialEq, Clone)]
pub struct NmStatePluginErr_Args {
    pub r#kind: String,
    pub r#error_message: String,
    pub r#logs: Vec<String>,
}
#[derive(Serialize, Deserialize, Debug, PartialEq, Clone)]
pub struct GenerateConfigs_Reply {
    pub r#logs: Vec<String>,
    pub r#confs: Vec<String>,
}
impl varlink::VarlinkReply for GenerateConfigs_Reply {}
#[derive(Serialize, Deserialize, Debug, PartialEq, Clone)]
pub struct GenerateConfigs_Args {
    pub r#net_state: NetState,
}
pub trait Call_GenerateConfigs: VarlinkCallError {
    fn reply(
        &mut self,
        r#logs: Vec<String>,
        r#confs: Vec<String>,
    ) -> varlink::Result<()> {
        self.reply_struct(GenerateConfigs_Reply { r#logs, r#confs }.into())
    }
}
impl<'a> Call_GenerateConfigs for varlink::Call<'a> {}
pub trait VarlinkInterface {
    fn generate_configs(
        &self,
        call: &mut dyn Call_GenerateConfigs,
        r#net_state: NetState,
    ) -> varlink::Result<()>;
    fn call_upgraded(
        &self,
        _call: &mut varlink::Call,
        _bufreader: &mut dyn BufRead,
    ) -> varlink::Result<Vec<u8>> {
        Ok(Vec::new())
    }
}
pub trait VarlinkClientInterface {
    fn generate_configs(
        &mut self,
        r#net_state: NetState,
    ) -> varlink::MethodCall<GenerateConfigs_Args, GenerateConfigs_Reply, Error>;
}
#[allow(dead_code)]
pub struct VarlinkClient {
    connection: Arc<RwLock<varlink::Connection>>,
}
impl VarlinkClient {
    #[allow(dead_code)]
    pub fn new(connection: Arc<RwLock<varlink::Connection>>) -> Self {
        VarlinkClient { connection }
    }
}
impl VarlinkClientInterface for VarlinkClient {
    fn generate_configs(
        &mut self,
        r#net_state: NetState,
    ) -> varlink::MethodCall<GenerateConfigs_Args, GenerateConfigs_Reply, Error>
    {
        varlink :: MethodCall :: < GenerateConfigs_Args , GenerateConfigs_Reply , Error > :: new (self . connection . clone () , "io.nmstate.plugin.GenerateConfigs" , GenerateConfigs_Args { r#net_state })
    }
}
#[allow(dead_code)]
pub struct VarlinkInterfaceProxy {
    inner: Box<dyn VarlinkInterface + Send + Sync>,
}
#[allow(dead_code)]
pub fn new(
    inner: Box<dyn VarlinkInterface + Send + Sync>,
) -> VarlinkInterfaceProxy {
    VarlinkInterfaceProxy { inner }
}
impl varlink::Interface for VarlinkInterfaceProxy {
    fn get_description(&self) -> &'static str {
        "interface io.nmstate.plugin\n\ntype NetIface (\n    name: string,\n    type: string\n)\n\ntype NetState (\n    interfaces: ?[]NetIface\n)\n\nmethod GenerateConfigs(net_state: NetState) -> (logs: []string, confs: []string)\n\nerror NmStatePluginErr (\n    kind: string,\n    error_message: string,\n    logs: []string\n)\n"
    }
    fn get_name(&self) -> &'static str {
        "io.nmstate.plugin"
    }
    fn call_upgraded(
        &self,
        call: &mut varlink::Call,
        bufreader: &mut dyn BufRead,
    ) -> varlink::Result<Vec<u8>> {
        self.inner.call_upgraded(call, bufreader)
    }
    fn call(&self, call: &mut varlink::Call) -> varlink::Result<()> {
        let req = call.request.unwrap();
        match req.method.as_ref() {
            "io.nmstate.plugin.GenerateConfigs" => {
                if let Some(args) = req.parameters.clone() {
                    let args: GenerateConfigs_Args =
                        match serde_json::from_value(args) {
                            Ok(v) => v,
                            Err(e) => {
                                let es = format!("{}", e);
                                let _ =
                                    call.reply_invalid_parameter(es.clone());
                                return Err(varlink::context!(
                                    varlink::ErrorKind::SerdeJsonDe(es)
                                )
                                .into());
                            }
                        };
                    self.inner.generate_configs(
                        call as &mut dyn Call_GenerateConfigs,
                        args.r#net_state,
                    )
                } else {
                    call.reply_invalid_parameter("parameters".into())
                }
            }
            m => call.reply_method_not_found(String::from(m)),
        }
    }
}
